
This test service simulates machine-to-machine communication and returns client tokens that are used.

[mermaid]
....
flowchart LR
n(Client):::external --> t
subgraph onecx-test-oidc
subgraph microservice1
t(TestRestController):::service --> i(Client of backend service):::service
end
i -- oidc --> b
subgraph microservice2
b(BackendRestController):::service
end
end
....

=== Usage

==== Local testing

Download the docker image
[source,shell,subs=attributes+]
----
docker pull ghcr.io/onecx/onecx-test-oidc:main-native
----

Start docker container

[source,shell,subs=attributes+]
----
docker run --rm -p 8080:8080 \
-e TKIT_LOG_JSON_ENABLED=false \
-e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=https://keycloak:8080/realms/test \
-e QUARKUS_OIDC_CLIENT_CLIENT_ID=client-id \
-e QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET=client-secret \
-e QUARKUS_OIDC_AUTH_SERVER_URL=https://keycloak:8080/realms/test \
 ghcr.io/onecx/onecx-test-oidc:main-native
----

Environment variables:

* TKIT_LOG_JSON_ENABLED - determine whether to enable the JSON console formatting extension, which disables "normal" console formatting. https://1000kit.github.io/tkit-quarkus/current/tkit-quarkus/tkit-quarkus-log-json.html#tkit-quarkus-log-json_tkit-log-json-enabled[Link]
* QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL - The client base URL of the OpenID Connect (OIDC) server for client. https://quarkus.io/guides/all-config#quarkus-oidc-client_quarkus-oidc-client-auth-server-url[Link]
* QUARKUS_OIDC_CLIENT_CLIENT_ID - A unique OIDC client identifier. https://quarkus.io/guides/all-config#quarkus-oidc-client_quarkus-oidc-client-id[Link]
* QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET - The client secret. https://quarkus.io/guides/all-config#quarkus-oidc-client_quarkus-oidc-client-credentials-secret[Link]
* QUARKUS_OIDC_AUTH_SERVER_URL - The base URL of the OpenID Connect (OIDC) server. https://quarkus.io/guides/all-config#quarkus-oidc_quarkus-oidc-auth-server-url[Link]

To get the client token, run the appropriate command
[source,shell,subs=attributes+]
----
curl http://localhost:8080/test/oidc/client
----
